### ISSUE TITLE
Win11，GUI RC2报错，1.17正常

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1046]
问题类型：PaddleX可视化客户端  

**PaddleX GUI版本**  
PaddleX GUI  RC2版本

**问题描述**  

===================================  
```

This log file path is D:\paddlex_workspaceRC2\projects\P0006\T0008\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
D:\PaddleX2.0.0rc2_windows10\paddle\distributed\parallel.py:120: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  "Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything."
D:\PaddleX2.0.0rc2_windows10\paddle\tensor\creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
D:\PaddleX2.0.0rc2_windows10\paddle\tensor\creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:

import numpy as np
from paddle.io import DataLoader, Dataset

class RandomDataset(Dataset):
    def __getitem__(self, idx):
        data = np.random.random((2, 3)).astype('float32')

        return data

    def __len__(self):
        return 10

dataset = RandomDataset()
loader = DataLoader(dataset, batch_size=1)
data = next(loader())

In Paddle <= 2.0, data is in format '[Tensor(shape=(1, 2, 3), dtype=float32)]', and in Paddle >= 2.1, data is in format 'Tensor(shape=(1, 2, 3), dtype=float32)'

Process Process-1:2:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 71, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\detection.py", line 225, in train
  File "D:\PaddleX2.0.0rc2_windows10\paddlex\cv\models\detector.py", line 286, in train
    use_vdl=use_vdl)
  File "D:\PaddleX2.0.0rc2_windows10\paddlex\cv\models\base.py", line 337, in train_loop
    loss.backward()
  File "<decorator-gen-123>", line 2, in backward
  File "D:\PaddleX2.0.0rc2_windows10\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\PaddleX2.0.0rc2_windows10\paddle\fluid\framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "D:\PaddleX2.0.0rc2_windows10\paddle\fluid\dygraph\varbase_patch_methods.py", line 239, in backward
    framework._dygraph_tracer())
OSError: (External)  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  (at C:/home/workspace/Paddle_release2/paddle/fluid/operators/conv_cudnn_op.cu:790)


```
--------------------
GUI RC2报错，
1.17 反而正常

目录设置home地址是
D:\PaddleX2.0.0rc2_windows10
报错的地址是
C:/home/workspace/Paddle_release2/paddle/fluid/operators/conv_cudnn_op.cu
不存在这个目录

**Comment by FlyingQianMM** [comment]
PaddleX2.0.0rc2需要cuda 11.2，cudnn8。

可以先试下paddlex api开发模式。

**Comment by monkeycc** [comment]
nvidia-smi


```

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 471.68       Driver Version: 471.68       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P8    10W /  N/A |    164MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```


nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Wed_Jul_14_19:47:52_Pacific_Daylight_Time_2021
Cuda compilation tools, release 11.4, V11.4.100
Build cuda_11.4.r11.4/compiler.30188945_0

cudnn-11.4-windows-x64-v8.2.2.26

系统是 cuda 11.4   cudnn8.2.2.26  
是这个问题导致 ？

**Comment by monkeycc** [comment]
已经解决

 NVIDIA-SMI 465.89       Driver Version: 465.89       CUDA Version: 11.3

Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:15:10_Pacific_Standard_Time_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0
