### ISSUE TITLE
训练报错cudaErrorNoKernelImageForDevice:

### ISSUE THREAD

**Issue by wang971124** [PaddlePaddle/PaddleX#1071]
问题类型：模型训练  
训练报错
**PaddleX版本**  
您使用的PaddleX版本
paddleGUI2.0.0rc2
**问题描述**  
训练过程中出现SystemError: (Fatal) Operator gaussian_random raises an class thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. 
====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应

**Comment by wang971124** [comment]
补充：
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:32_Central_Daylight_Time_2017
Cuda compilation tools, release 9.0, V9.0.176

**Comment by FlyingQianMM** [comment]
paddleGUI2.0.0rc2 需要使用CUDA11.2 和CUDNN8.0

**Comment by wang971124** [comment]
> paddleGUI2.0.0rc2 需要使用CUDA11.2 和CUDNN8.0

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_22:08:44_Pacific_Standard_Time_2021
Cuda compilation tools, release 11.2, V11.2.152
重装了cuda还是同样问题

**Comment by FlyingQianMM** [comment]
cudnn版本有更新吗？相应驱动也需要更新下

**Comment by wang971124** [comment]
我更换了1.1.7可以正常运行了，2.0.0还是不可以，驱动和cudnn以及cuda都已经更到对应版本；

**Comment by lubupang** [comment]
显卡不支持CUDA,windows支持 CPU运行么

**Comment by lubupang** [comment]
> 



> 

11.6的CUDA可以么
