### ISSUE TITLE
PaddleX GUI 2.1.0 无法开启训练

### ISSUE THREAD

**Issue by littleantsos** [PaddlePaddle/PaddleX#1617]
## 描述问题
环境：
CUDA 11.2
CUDNN 8.2.1  (但是paddleX GUI设置里面显示的为8.1.0）
paddle 2.2.1.post112
paddleX gui 2.1.0
paddleX 2.1.0
Win10  
NVIDIA GeForce GTX950M  算力5.0
python 3.7.9

pytorch 是否对这个有影响

## 复现

无法启动训练，一直报下面的错误，Cuda 和paddle也尝试了多个版本，都未解决。
paddlex的设置界面cudnn显示版本为8.1.0，一直不变，不知道是否是要用cudnn8.1.0

This log file path is C:\work\AI\paddlex_workspace\projects\P0001\T0009\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
C:\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Process Process-1:5:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 73, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\detection.py", line 224, in train
  File "C:\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 952, in __init__
    feature_maps=[7, 13, 16])
  File "C:\PaddleX_GUI_2.1.0_win10\paddlex\cv\models\detector.py", line 101, in _get_backbone
    backbone = getattr(ppdet.modeling, backbone_name)(**params)
  File "C:\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\backbones\mobilenet_v3.py", line 372, in __init__
    name="conv1")
  File "C:\PaddleX_GUI_2.1.0_win10\paddlex\ppdet\modeling\backbones\mobilenet_v3.py", line 66, in __init__
    bias_attr=False)
  File "C:\PaddleX_GUI_2.1.0_win10\paddle\nn\layer\conv.py", line 656, in __init__
    data_format=data_format)
  File "C:\PaddleX_GUI_2.1.0_win10\paddle\nn\layer\conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "C:\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\layers.py", line 424, in create_parameter
    default_initializer)
  File "C:\PaddleX_GUI_2.1.0_win10\paddle\fluid\layer_helper_base.py", line 378, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "C:\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 3137, in create_parameter
    initializer(param, self)
  File "C:\PaddleX_GUI_2.1.0_win10\paddle\fluid\initializer.py", line 366, in __call__
    stop_gradient=True)
  File "C:\PaddleX_GUI_2.1.0_win10\paddle\fluid\framework.py", line 3167, in append_op
    kwargs.get("stop_gradient", False))
  File "C:\PaddleX_GUI_2.1.0_win10\paddle\fluid\dygraph\tracer.py", line 45, in trace_op
    not stop_gradient)
SystemError: (Fatal) Operator gaussian_random raises an class thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at ..\paddle\fluid\imperative\tracer.cc:221)

**Comment by lailuboy** [comment]
显卡是什么样的，点程序的设置看下显示的cuda和cudnn版本分别是多少

**Comment by littleantsos** [comment]
![image](https://user-images.githubusercontent.com/9715506/196081811-790885bb-0a48-4f3c-8926-7426e109c63c.png)
NVIDIA GeForce GTX950M

这个cuda和cudnn里的版本我换了几个，目前是用的这个，也是同样的问题， 

cudnn之前是默认的paddlex里的，最后我把paddlex目录里的cudnn dll替换了 ， 也还是同样的错误 

这个跟pytorch有关系吗，因为我查了下，很多都是pytorch的相关回答

**Comment by littleantsos** [comment]
因为我是从没基础，但是项目需要，所以您可以告诉我下这个问题引起的可能原因，我来一个个来排除

**Comment by lailuboy** [comment]
问题就是显卡对应的驱动不对，cuda和cudnn，程序是用的paddlex目录中的库。环境上执行一下nvidia-smi结果呢。

**Comment by littleantsos** [comment]
![image](https://user-images.githubusercontent.com/9715506/196083898-8b5d94c1-7862-42ad-91fa-9387da81f0db.png)

**Comment by littleantsos** [comment]
解决了，原来是我的电脑显卡太低，不配运行GUI2.1.0 ,    换成 GUI1.1.7  CUDA 10.2就可以了
