### ISSUE TITLE
没有用GPU，但是一直CUDAError

### ISSUE THREAD

**Issue by Jameskywalker** [PaddlePaddle/PaddleX#409]
问题类型：PaddleX可视化客户端  
**问题描述**  

===================================  

请在这里描述您在使用GUI过程中的问题
包括训练内置的果蔬分类，一直失败
Error Message Summary:
----------------------
ExternalError:  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.
  [Advise: Please search for the error code(35) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] at (D:\1.8.4\paddle\paddle\fluid\platform\gpu_info.cc:65)
  [operator < fill_constant > error]
但是我已经点选不用GPU

**Comment by jiangjiajun** [comment]
你的电脑里面有GPU吗

**Comment by Jameskywalker** [comment]
gtx1050笔记本版是不是太差了所以无法运行发自我的华为手机-------- 原始邮件 --------发件人： Jason <notifications@github.com>日期： 2020年11月19日周四 20:11收件人： PaddlePaddle/PaddleX <PaddleX@noreply.github.com>抄送： Jameskywalker <haozai2001@163.com>, Author <author@noreply.github.com>主    题： Re: [PaddlePaddle/PaddleX] 没有用GPU，但是一直CUDAError (#409)

你的电脑里面有GPU吗

**Comment by jiangjiajun** [comment]
你好，如果当前在CPU上运行也会有问题，麻烦尝试下下面的方式来解决

> 1.找到PaddleX的安装目录，删除里面的paddle文件夹
> 2.下载cpu版本的paddle压缩包，解压后将里面的paddle文件夹复制到PaddleX的安装目录  链接: https://pan.baidu.com/s/1sr1EBfe8FTvZZOdszs2tIA  密码: re9d
> 3. 重新开始任务训练（替换后只能训练CPU的任务）

**Comment by Jameskywalker** [comment]
解决了^_^谢谢
