### ISSUE TITLE
使用高稳定性服务化部署，use_chart_recognition 报错

### ISSUE THREAD

**Issue by SnCecilia** [PaddlePaddle/PaddleX#4203]
## Checklist:

- [ ✅ ] 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
- [ ✅ ] 翻阅[FAQ](https://paddlepaddle.github.io/PaddleX/main/FAQ.html)
- [ ✅ ] 翻阅[PaddleX 文档](https://paddlepaddle.github.io/PaddleX/main/index.html)
- [ ] 确认bug是否在新版本里还未修复

## 描述问题
下载的sdk：
通用版面解析 v3 | paddlex_hps_PP-StructureV3_sdk.tar.gz
拉取的镜像：
docker pull ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlex/hps:paddlex3.0.1-gpu

使用高稳定性服务化部署后，在客户端能成功运行client.py脚本。
但是，尝试加入 use_chart_recognition 参数后，客户端报错：
Error code: 500
Error message: Internal server error

服务端日志报错信息如下：
/paddlex/py310/lib/python3.10/site-packages/paddlex/inference/models/doc_vlm/predictor.py:247: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach(), rather than paddle.to_tensor(sourceTensor).
  paddle.to_tensor(input_dict[k], place=self.device)
Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
[   ERROR] [2025-06-14 07:47:18,285] [d53064befa054ab89a88d4e8abcfd6e2] [6d1b540a-e808-42ca-a6f9-9f86167f010b] - Unhandled exception
Traceback (most recent call last):
  File "/paddlex/py310/lib/python3.10/site-packages/paddlex_hps_server/base_model.py", line 88, in execute
    result_or_output = self.run(input_, log_id)
  File "/paddlex/var/paddlex_model_repo/layout-parsing/1/model.py", line 85, in run
    result = list(
  File "/paddlex/py310/lib/python3.10/site-packages/paddlex/inference/pipelines/_parallel.py", line 129, in predict
    yield from self._pipeline.predict(
  File "/paddlex/py310/lib/python3.10/site-packages/paddlex/inference/pipelines/layout_parsing/pipeline_v2.py", line 1277, in predict
    for chart_res_batch in self.chart_recognition_model(
  File "/paddlex/py310/lib/python3.10/site-packages/paddlex/inference/models/base/predictor/base_predictor.py", line 211, in __call__
    yield from self.apply(input, **kwargs)
  File "/paddlex/py310/lib/python3.10/site-packages/paddlex/inference/models/base/predictor/base_predictor.py", line 267, in apply
    prediction = self.process(batch_data, **kwargs)
  File "/paddlex/py310/lib/python3.10/site-packages/paddlex/inference/models/doc_vlm/predictor.py", line 144, in process
    preds = self.infer.generate(data, **kwargs)
  File "/paddlex/py310/lib/python3.10/site-packages/paddlex/inference/models/doc_vlm/modeling/GOT_ocr_2_0.py", line 821, in generate
    generated_ids = super().generate(
  File "/paddlex/py310/lib/python3.10/site-packages/decorator.py", line 235, in fun
    return caller(func, *(extras + args), **kw)
  File "/paddlex/py310/lib/python3.10/site-packages/paddle/base/dygraph/base.py", line 400, in _decorate_function
    return func(*args, **kwargs)
  File "/paddlex/py310/lib/python3.10/site-packages/paddlex/inference/models/common/vlm/generation/utils.py", line 1114, in generate
    return self.greedy_search(
  File "/paddlex/py310/lib/python3.10/site-packages/paddlex/inference/models/common/vlm/generation/utils.py", line 1283, in greedy_search
    outputs = self(**model_inputs)
  File "/paddlex/py310/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1567, in __call__
    return self.forward(*inputs, **kwargs)
  File "/paddlex/py310/lib/python3.10/site-packages/paddlex/inference/models/doc_vlm/modeling/GOT_ocr_2_0.py", line 729, in forward
    outputs = self.qwen2(
  File "/paddlex/py310/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1567, in __call__
    return self.forward(*inputs, **kwargs)
  File "/paddlex/py310/lib/python3.10/site-packages/paddlex/inference/models/doc_vlm/modeling/GOT_ocr_2_0.py", line 584, in forward
    cnn_feature = vision_tower_high(image)
  File "/paddlex/py310/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1567, in __call__
    return self.forward(*inputs, **kwargs)
  File "/paddlex/py310/lib/python3.10/site-packages/paddlex/inference/models/doc_vlm/modeling/GOT_ocr_2_0.py", line 161, in forward
    x = self.patch_embed(x)
  File "/paddlex/py310/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1567, in __call__
    return self.forward(*inputs, **kwargs)
  File "/paddlex/py310/lib/python3.10/site-packages/paddlex/inference/models/doc_vlm/modeling/GOT_ocr_2_0.py", line 464, in forward
    x = self.proj(x)
  File "/paddlex/py310/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1567, in __call__
    return self.forward(*inputs, **kwargs)
  File "/paddlex/py310/lib/python3.10/site-packages/paddle/nn/layer/conv.py", line 742, in forward
    out = F.conv._conv_nd(
  File "/paddlex/py310/lib/python3.10/site-packages/paddle/nn/functional/conv.py", line 150, in _conv_nd
    pre_bias = _C_ops.conv2d(
OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED. 
  [Hint: 'CUDNN_STATUS_EXECUTION_FAILED'.  The GPU program failed to execute. This is usually caused by a failure to launch some cuDNN kernel on the GPU, which can occur for multiple reasons.  To correct, check that the hardware, an appropriate version of the driver, and the cuDNN library are correctly installed.  Otherwise, this may indicate an internal error/bug in the library.  ] (at ../paddle/phi/kernels/gpudnn/conv_cudnn_v7.h:791)

client.py：
#!/usr/bin/env python

import argparse
import sys
from pathlib import Path

from paddlex_hps_client import triton_request, utils
from tritonclient import grpc as triton_grpc

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--file", type=str, required=True)
    parser.add_argument("--file-type", type=int, choices=[0, 1])
    parser.add_argument("--url", type=str, default="localhost:8001")
    parser.add_argument("--use_chart_recognition", action="store_true", help="是否启用图表识别")
    
    args = parser.parse_args()

    client = triton_grpc.InferenceServerClient(args.url)
    input_ = {"file": utils.prepare_input_file(args.file)}
    if args.file_type is not None:
        input_["fileType"] = args.file_type
    if args.use_chart_recognition:
        input_["useChartRecognition"] = True
    output = triton_request(client, "layout-parsing", input_)
    if output["errorCode"] != 0:
        print(f"Error code: {output['errorCode']}", file=sys.stderr)
        print(f"Error message: {output['errorMsg']}", file=sys.stderr)
        sys.exit(1)
    result = output["result"]
    for i, res in enumerate(result["layoutParsingResults"]):
        print(res["prunedResult"])
        md_dir = Path(f"markdown_{i}")
        md_dir.mkdir(exist_ok=True)
        (md_dir / "doc.md").write_text(res["markdown"]["text"])
        for img_path, img in res["markdown"]["images"].items():
            img_path = md_dir / img_path
            img_path.parent.mkdir(parents=True, exist_ok=True)
            utils.save_output_file(img, img_path)
        print(f"Markdown document saved at {md_dir / 'doc.md'}")
        for img_name, img in res["outputImages"].items():
            img_path = f"{img_name}_{i}.jpg"
            utils.save_output_file(img, img_path)
            print(f"Output image saved at {img_path}")

if __name__ == "__main__":
    main()

执行命令：
python3 client.py --file test_chart.png --file-type 1 --url 10.2.230.155:8081 【成功返回解析结果】
python3 client.py --file test_chart.png --file-type 1 --url 10.2.230.155:8081 --use_chart_recognition   【报错】

## 复现

1. 高性能推理

    * 您是否完全按照[高性能推理文档教程](https://paddlepaddle.github.io/PaddleX/main/pipeline_deploy/high_performance_inference.html)跑通了流程？
    * 没有使用高性能推理

2. 服务化部署

    * 您是否完全按照[服务化部署文档教程](https://paddlepaddle.github.io/PaddleX/main/pipeline_deploy/serving.html)跑通了流程？
    * 是

    * 您在服务化部署中是否有使用高性能推理插件？
    * 否

    * 您使用了哪一种服务化部署方案？
    * 高稳定性服务化部署

    * 如果是多语言调用的问题，请给出调用示例子。

3. 端侧部署
    * 您是否完全按照[端侧部署文档教程](https://paddlepaddle.github.io/PaddleX/main/pipeline_deploy/on_device_deployment.html)跑通了流程？

    * 您使用的端侧设备是？对应的PaddlePaddle版本和PaddleLite版本分别是什么？

3. 您使用的**模型**和**数据集**是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle、PaddleX版本号、Python版本号

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Linux

4. 请问您使用的CUDA/cuDNN的版本号是？
CUDA Version: 12.4

**Comment by cuicheng01** [comment]
机器的显存多大呢？非服务化部署直接运行会报错吗？

**Comment by SnCecilia** [comment]
> 机器的显存多大呢？非服务化部署直接运行会报错吗？
用的是一张4090，24g显存，只开了一个实例。非服务化部署直接运行不会报错

**Comment by cuicheng01** [comment]
好的，问题我们确认下，另外通过`paddlex --serve`的方式，在你这边有问题吗

**Comment by SnCecilia** [comment]
> 好的，问题我们确认下，另外通过`paddlex --serve`的方式，在你这边有问题吗

这种方式也没问题，可以正常解析

**Comment by Bobholamovic** [comment]
请问使用的显卡是0号卡吗

**Comment by SnCecilia** [comment]
> 请问使用的显卡是0号卡吗

3号

**Comment by Bobholamovic** [comment]
图表模型使用动态图推理，而目前飞桨框架存在bug，如果使用非零号卡做动态图推理可能会有问题，日志中的错误就是试图使用一张卡上的tensor与另一张卡上的tensor执行计算导致的。这个bug预计将在飞桨框架的下一个版本（3.1.0）修复，届时paddlex也会做出适配。抱歉给你带来不便，目前请暂时在0号卡上使用～

**Comment by SnCecilia** [comment]
> 图表模型使用动态图推理，而目前飞桨框架存在bug，如果使用非零号卡做动态图推理可能会有问题，日志中的错误就是试图使用一张卡上的tensor与另一张卡上的tensor执行计算导致的。这个bug预计将在飞桨框架的下一个版本（3.1.0）修复，届时paddlex也会做出适配。抱歉给你带来不便，目前请暂时在0号卡上使用～

感谢，问题暂时解决，期待你们的新版本～

**Comment by SnCecilia** [comment]
> 

请问现在可以在非0号卡，以及多张卡上使用了吗？需要更新到什么版本？

**Comment by cuicheng01** [comment]
@Bobholamovic 辛苦确认下这个问题

**Comment by Bobholamovic** [comment]
> > 
> 
> 请问现在可以在非0号卡，以及多张卡上使用了吗？需要更新到什么版本？

还是不行 我们尚未更新框架的版本 预计将在近期支持

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
