### ISSUE TITLE
DocBee2大模型服务化部署显存占用不正常

### ISSUE THREAD

**Issue by Gplus-SYS** [PaddlePaddle/PaddleX#4471]
## 描述问题
系统为Ubuntu22.04，GPU为RTX4090，当按照以下流程进行DocBee2多模态大模型的服务化部署时，首次部署成功可以正常访问，显存占用约16G，一切正常
①　克隆PaddleX仓库，[参考文档](https://github.com/PaddlePaddle/PaddleX/issues#21-dockerpaddlex)
git clone https://github.com/PaddlePaddle/PaddleX.git
cd PaddleX
②　创建虚拟环境
conda create -n paddlex python=3.10 -y
conda activate paddlex
python -m pip install paddlepaddle-gpu==3.1.1 -i https://www.paddlepaddle.org.cn/packages/stable/cu118/
③　安装PaddleX
pip install -e ".[base]"
④　安装服务化部署插件
paddlex --install serving
⑤　CLI一键启动服务(自动下载模型)
paddlex --serve --pipeline doc_understanding

一周后结束进程，通过paddlex --serve --pipeline doc_understanding重新启动失败，报错如下：
(paddlex) lenovo@lenovo-ThinkStation-P3-Tower:~$ paddlex --serve --pipeline doc_understanding
Creating model: ('PP-DocBee2-3B', None)
Using official model (PP-DocBee2-3B), the model files will be automatically downloaded and saved in /home/lenovo/.paddlex/official_models.
Fetching 9 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 13098.10it/s]
/home/lenovo/anaconda3/envs/paddlex/lib/python3.10/site-packages/paddle/utils/cpp_extension/extension_utils.py:717: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
W0820 18:00:03.037302 135746 gpu_resources.cc:114] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.9, Runtime API Version: 11.8
The `unk_token` parameter needs to be defined: we use `eos_token` by default.
Loading configuration file /home/lenovo/.paddlex/official_models/PP-DocBee2-3B/config.json
Loading weights file /home/lenovo/.paddlex/official_models/PP-DocBee2-3B/model_state.pdparams
Loaded weights file from disk, setting weights to model.
`Qwen2_5_VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Traceback (most recent call last):
  File "/home/lenovo/anaconda3/envs/paddlex/bin/paddlex", line 33, in <module>
    sys.exit(load_entry_point('paddlex', 'console_scripts', 'paddlex')())
  File "/home/lenovo/PaddleX/paddlex/__main__.py", line 26, in console_entry
    main()
  File "/home/lenovo/PaddleX/paddlex/paddlex_cli.py", line 481, in main
    serve(
  File "/home/lenovo/PaddleX/paddlex/paddlex_cli.py", line 380, in serve
    pipeline = create_pipeline(
  File "/home/lenovo/PaddleX/paddlex/inference/pipelines/__init__.py", line 166, in create_pipeline
    pipeline = BasePipeline.get(pipeline_name)(
  File "/home/lenovo/PaddleX/paddlex/utils/deps.py", line 202, in _wrapper
    return old_init_func(self, *args, **kwargs)
  File "/home/lenovo/PaddleX/paddlex/inference/pipelines/doc_understanding/pipeline.py", line 61, in __init__
    self.doc_understanding_model = self.create_model(doc_understanding_model_config)
  File "/home/lenovo/PaddleX/paddlex/inference/pipelines/base.py", line 105, in create_model
    model = create_predictor(
  File "/home/lenovo/PaddleX/paddlex/inference/models/__init__.py", line 77, in create_predictor
    return BasePredictor.get(model_name)(
  File "/home/lenovo/PaddleX/paddlex/inference/models/doc_vlm/predictor.py", line 54, in __init__
    self.infer, self.processor = self._build(**kwargs)
  File "/home/lenovo/PaddleX/paddlex/inference/models/doc_vlm/predictor.py", line 115, in _build
    model = PPDocBee2Inference.from_pretrained(
  File "/home/lenovo/PaddleX/paddlex/inference/models/common/vlm/transformers/model_utils.py", line 1821, in from_pretrained
    model = cls(config, *init_args, **model_kwargs)
  File "/home/lenovo/PaddleX/paddlex/inference/models/common/tokenizer/tokenizer_utils.py", line 330, in __impl__
    init_func(self, *args, **kwargs)
  File "/home/lenovo/PaddleX/paddlex/inference/models/doc_vlm/modeling/qwen2_5_vl.py", line 2978, in __init__
    self.model = Qwen2_5_VLModel(config)
  File "/home/lenovo/PaddleX/paddlex/inference/models/common/tokenizer/tokenizer_utils.py", line 330, in __impl__
    init_func(self, *args, **kwargs)
  File "/home/lenovo/PaddleX/paddlex/inference/models/doc_vlm/modeling/qwen2_5_vl.py", line 1966, in __init__
    [
  File "/home/lenovo/PaddleX/paddlex/inference/models/doc_vlm/modeling/qwen2_5_vl.py", line 1967, in <listcomp>
    Qwen2_5_VLDecoderLayer(config, layer_idx)
  File "/home/lenovo/PaddleX/paddlex/inference/models/doc_vlm/modeling/qwen2_5_vl.py", line 1645, in __init__
    self.mlp = Qwen2MLP(config)
  File "/home/lenovo/PaddleX/paddlex/inference/models/doc_vlm/modeling/qwen2_5_vl.py", line 1065, in __init__
    self.gate_proj = Linear(
  File "/home/lenovo/anaconda3/envs/paddlex/lib/python3.10/site-packages/paddle/nn/layer/common.py", line 208, in __init__
    self.weight = self.create_parameter(
  File "/home/lenovo/anaconda3/envs/paddlex/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 837, in create_parameter
    return self._helper.create_parameter(
  File "/home/lenovo/anaconda3/envs/paddlex/lib/python3.10/site-packages/paddle/base/layer_helper_base.py", line 442, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/lenovo/anaconda3/envs/paddlex/lib/python3.10/site-packages/paddle/base/framework.py", line 4673, in create_parameter
    initializer(param, self)
  File "/home/lenovo/anaconda3/envs/paddlex/lib/python3.10/site-packages/paddle/nn/initializer/initializer.py", line 69, in __call__
    return self.forward(param, block)
  File "/home/lenovo/anaconda3/envs/paddlex/lib/python3.10/site-packages/paddle/nn/initializer/xavier.py", line 159, in forward
    out_var = _C_ops.uniform(
MemoryError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::pybind::eager_api_uniform(_object*, _object*, _object*)
1   uniform_ad_func(paddle::experimental::IntArrayBase<paddle::Tensor>, phi::DataType, paddle::experimental::ScalarBase<paddle::Tensor>, paddle::experimental::ScalarBase<paddle::Tensor>, int, phi::Place)
2   paddle::experimental::uniform(paddle::experimental::IntArrayBase<paddle::Tensor> const&, phi::DataType, paddle::experimental::ScalarBase<paddle::Tensor> const&, paddle::experimental::ScalarBase<paddle::Tensor> const&, int, phi::Place const&)
3   void phi::UniformKernel<phi::dtype::bfloat16, phi::GPUContext>(phi::GPUContext const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, phi::DataType, paddle::experimental::ScalarBase<phi::DenseTensor> const&, paddle::experimental::ScalarBase<phi::DenseTensor> const&, int, phi::DenseTensor*)
4   phi::dtype::bfloat16* phi::DeviceContext::Alloc<phi::dtype::bfloat16>(phi::TensorBase*, unsigned long, bool) const
5   phi::DenseTensor::AllocateFrom(phi::Allocator*, phi::DataType, unsigned long, bool)
6   paddle::memory::allocation::Allocator::Allocate(unsigned long)
7   paddle::memory::allocation::StatAllocator::AllocateImpl(unsigned long)
8   paddle::memory::allocation::Allocator::Allocate(unsigned long)
9   paddle::memory::allocation::Allocator::Allocate(unsigned long)
10  std::string phi::enforce::GetCompleteTraceBackString<std::string >(std::string&&, char const*, int)
11  common::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 462.000000MB memory on GPU 0, 23.411560GB memory has been allocated and available memory is only 107.437500MB.

整个模型大小仅3.75B，24G显存无法启动。另外通过paddlex --serve --pipeline doc_understanding自动下载的模型与Hugging Face中开源的模型文件似乎不同？

**Comment by ylu535** [comment]
一样的问题 
CUDA12.6，
H20 96G 
paddleocr                3.1.1
paddlepaddle-gpu         3.1.1
paddlex                  3.1.3
一下午没跑起来
Out of memory error on GPU 0. Cannot allocate 462.000000MB memory on GPU 0, 94.856506GB memory has been allocated and available memory is only 249.812500MB.

**Comment by cuicheng01** [comment]
问题已收到，我们再排查下看是否可以复现问题

**Comment by Bobholamovic** [comment]
@ylu535 我们注意到paddlepaddle-gpu 3.1在H20、A100上确实存在这个问题，目前我们也正在排查问题中，抱歉给你带来了不便。建议可以尝试降级padlepaddle-gpu 3.0。

**Comment by Bobholamovic** [comment]
@Jiahao-Guan 这个模型比较大，4090的显存应该不太够，请准备32GB以上显存的GPU～

**Comment by ylu535** [comment]
> [@ylu535](https://github.com/ylu535) 我们注意到paddlepaddle-gpu 3.1在H20、A100上确实存在这个问题，目前我们也正在排查问题中，抱歉给你带来了不便。建议可以尝试降级padlepaddle-gpu 3.0。

@Bobholamovic 试了一下H20降级到paddlepaddle-gpu 3.0.0还是同样的问题，重新换了L20+padlepaddle-gpu 3.0以及padlepaddle-gpu 3.1.1也试过，也是同样的问题

**Comment by Bobholamovic** [comment]
我们将定位是否是paddlex而不是框架的问题，感谢你的反馈

**Comment by Bobholamovic** [comment]
我们排查到这是因为huggingface源的模型配置文件（`config.json`）有误，导致程序在初始化模型时试图创建过多的隐藏层，进而导致OOM。请尝试删除`~/.paddlex/official_models/PP-DocBee2-3B`的模型后重新运行程序（将自动下载修复后的官方模型）。

**Comment by Gplus-SYS** [comment]
> 我们排查到这是因为huggingface源的模型配置文件（`config.json`）有误，导致程序在初始化模型时试图创建过多的隐藏层，进而导致OOM。请尝试删除`~/.paddlex/official_models/PP-DocBee2-3B`的模型后重新运行程序（将自动下载修复后的官方模型）。

尝试了一下，可以正常启动了，感谢您的帮助！
