### ISSUE TITLE
使用paddleX训练内置的图像识别的模型一直失败

### ISSUE THREAD

**Issue by pinkDOUDOU** [PaddlePaddle/PaddleX#458]
问题类型：PaddleX可视化客户端  
**问题描述**  
我使用paddleX训练内置的蔬菜分类的模型，使用的CPU训练，一直不能成功
===================================  
This log file path is E:\paddlex\projects\P0002\T0007\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
!!! The CPU_NUM is not specified, you should set CPU_NUM in the environment variable list.
CPU_NUM indicates that how many CPUPlace are used in the current task.
And if this parameter are set as N (equal to the number of physical CPU core) the program may be faster.

export CPU_NUM=8 # for example, set CPU_NUM as number of physical CPU core which is 8.

!!! The default number of CPU_NUM=1.
E:\paddlex\PaddleX\paddle\fluid\executor.py:1070: UserWarning: The following exception is not an EOF exception.
Process Process-1:8:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 68, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\classification.py", line 134, in train
  File "site-packages\paddlex\cv\models\classifier.py", line 195, in train
  File "site-packages\paddlex\cv\models\base.py", line 244, in net_initialize
  File "site-packages\paddle\fluid\executor.py", line 1071, in run
  File "site-packages\six.py", line 703, in reraise
  File "site-packages\paddle\fluid\executor.py", line 1066, in run
  File "site-packages\paddle\fluid\executor.py", line 1154, in _run_impl
  File "site-packages\paddle\fluid\executor.py", line 1229, in _run_program
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "site-packages\paddle\fluid\framework.py", line 2679, in _prepend_op
  File "site-packages\paddle\fluid\initializer.py", line 147, in __call__
  File "site-packages\paddle\fluid\framework.py", line 2449, in create_var
  File "site-packages\paddle\fluid\layer_helper_base.py", line 420, in set_variable_initializer
  File "site-packages\paddle\fluid\optimizer.py", line 457, in _add_accumulator
  File "site-packages\paddle\fluid\optimizer.py", line 1033, in _create_accumulators
  File "site-packages\paddle\fluid\optimizer.py", line 544, in _create_optimization_pass
  File "site-packages\paddle\fluid\optimizer.py", line 722, in apply_gradients
  File "site-packages\paddle\fluid\optimizer.py", line 752, in apply_optimize
  File "site-packages\paddle\fluid\optimizer.py", line 838, in minimize
  File "site-packages\paddle\fluid\dygraph\base.py", line 277, in __impl__
  File "<decorator-gen-66>", line 2, in minimize
  File "site-packages\paddlex\cv\models\classifier.py", line 81, in build_net
  File "site-packages\paddlex\cv\models\base.py", line 105, in build_program
  File "site-packages\paddlex\cv\models\classifier.py", line 187, in train
  File "paddlexui\pms\model_tasks\train\classification.py", line 134, in train
  File "paddlexui\pms\model_tasks\tasks.py", line 68, in _call_paddlex_train
  File "multiprocessing\process.py", line 99, in run
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\spawn.py", line 118, in _main
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py", line 43, in _freeze_support
  File "paddlexui\PaddleXCore.py", line 39, in main
  File "paddlexui\PaddleX.py", line 18, in <module>

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.
  [Advise: Please search for the error code(35) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] at (D:\1.8.4\paddle\paddle\fluid\platform\gpu_info.cc:65)
  [operator < fill_constant > error]

请在这里描述您在使用GUI过程中的问题

**Comment by lailuboy** [comment]
是因为您的环境上有GPU，但是驱动版本太低。
如果只是想用CPU训练可以按照下面这个issue的方法解决
https://github.com/PaddlePaddle/PaddleX/issues/409

**Comment by pinkDOUDOU** [comment]
> 是因为您的环境上有GPU，但是驱动版本太低。
> 如果只是想用CPU训练可以按照下面这个issue的方法解决
> #409

非常感谢，已解决！但后续如果想要使用paddle提供的GPU算力的话，可以直接从paddleX上操作吗

**Comment by lailuboy** [comment]
使用GPU算力话可以使用AIStudio( https://aistudio.baidu.com )，可以在上面使用PaddleX。
